apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_server_address: "http://eureka-0.eureka:8762/eureka"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_server_url: "http://config-server-svc"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  hostname: "mysql-0.mysql"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-services-cm
data:
  product_service_url: "http://product-service-svc"
  payment_service_url: "http://payment-service-svc"
  order_service_url: "http://order-service-svc"
