# Default port Config Sever => 9296
server:
  port: 9296

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SIBKM-DevSecOps/config-app.git
          clone-on-start: true
          default-label: master